### ISSUE TITLE
Exception when querying registries after adding a new service (SSAP  window)

### ISSUE THREAD

**Issue by mmpcn** [SPLAT-VO/starjava#7]
In SSAP Window 
 -> Add new server  (enter values, add server)
 -> query registry : 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at uk.ac.starlink.splat.vo.SSAQueryBrowser.showParameters(SSAQueryBrowser.java:2603)
	at uk.ac.starlink.splat.vo.SSAQueryBrowser.updateParameters(SSAQueryBrowser.java:2620)
	at uk.ac.starlink.splat.vo.SSAQueryBrowser.propertyChange(SSAQueryBrowser.java:2567)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)

**Comment by mmpcn** [comment]
Bug corrected.
